version: '3.7'
services:
  jenkins:
    environment:
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASS=${JENKINS_PASS}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASS=${GITHUB_PASS}
      - DOCKERHUB_USER=${DOCKERHUB_USER}
      - DOCKERHUB_PASS=${DOCKERHUB_PASS}

    build:
      ./
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./files:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker