apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: charts/kube-prometheus-stack
      sourceRef:
        kind: GitRepository
        name: prometheus-charts
        namespace: prometheus

