apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: auth-image
  namespace: flux-system
spec:
  image: cptmutchell/auth-service
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: auth-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-image
  policy:
    numerical:
      order: asc