apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: auth-image
  namespace: flux-system
spec:
  image: cptmutchell/auth-service
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: auth-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-image
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: convert-image
  namespace: flux-system
spec:
  image: cptmutchell/convert-service
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: convert-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: convert-image
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: history-image
  namespace: flux-system
spec:
  image: cptmutchell/history-service
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: history-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: history-image
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui-image
  namespace: flux-system
spec:
  image: cptmutchell/cbr-ui
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ui-image
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---