- name: add postgres
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: install postgres
  kubernetes.core.helm:
    kubeconfig: "{{home}}/.kube/config"
    name: postgres
    chart_ref: bitnami/postgresql
    release_namespace: postgres
    create_namespace: true
    values_files:
      - "{{manifestCopyFolder}}/postgres.yml.j2"

- name: Create postgres secret
  k8s:
    kubeconfig: "{{home}}/.kube/config"
    state: present
    src: "{{manifestCopyFolder}}/{{item}}"
  with_items:
    - postgres-secret.yml.j2
