- name: add rabbit
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"


- name: Copy rabbit password hash script
  copy:
    dest: "{{home}}"
    src: hash_rabbit_pass.sh
    mode: 0605

- name: create password hash variable
  shell: "{{home}}/hash_rabbit_pass.sh {{rabbit.password}}"
  register: hash_rabbit

- name: Copy rabbit templates
  template:
    dest: "{{manifestCopyFolder}}"
    src: "{{item}}"
  with_items:
    - "{{rabbit.manifests}}"

- name: install rabbit
  kubernetes.core.helm:
    kubeconfig: "{{home}}/.kube/config"
    name: rabbit
    chart_ref: bitnami/rabbitmq
    release_namespace: "{{rabbit.ns}}"
    state: present
    create_namespace: true

    values_files:
      - "{{manifestCopyFolder}}/rabbit.yml.j2"

- name: Apply traefik ingress routes
  k8s:
    kubeconfig: "{{home}}/.kube/config"
    state: present
    src: "{{manifestCopyFolder}}/{{item}}"
  with_items:
    - rabbit-router.yml.j2
