- name: install dependecies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: Install pip
  apt:
    update_cache: yes
    state: latest
    pkg:
      - python3-pip
- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
- name: Install docker for module
  pip:
    name: "{{item}}"
    state: latest
    extra_args: --upgrade
    executable: pip3
  with_items:
    - docker
    - docker-compose

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Install docker-compose

  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

# To avoid dial unix /var/run/docker.sock: connect: permission denied
- name: Chmod docker.sock
  file:
    path: /var/run/docker.sock
    mode: 0666

