- name: create webhooks
  uri:
    url: "https://api.github.com/repos/{{item}}/hooks"
    method: POST
    body:
      name: web
      active: true
      events:
        - push
      config:
        url: "http://{{ansible_host}}:8080/github-webhook/"
        content_type: json
    body_format: json
    status_code: [201, 422]
    headers:
      Content-Type: "application/json"
      Accept: application/vnd.github.v3+json
      Authorization: "token {{github_token}}"
  with_items:
    - CPTMUTCHELL/cbr-currency-converter
    - CPTMUTCHELL/cbr-currency-converter-ui
